### ISSUE TITLE
In case not aware, MeshCat.jl

### ISSUE THREAD

**Issue by dehann** [JuliaPlots/WGLMakie.jl#15]
Hi, in case this was unknown, just mentioning a three.js visualization wrapper using websockets -- maybe slightly specific to robotics (see JuliaRobotics), but likely a lot to leverage for more general plotting:
https://github.com/rdeits/MeshCat.jl

cc @rdeits

**Comment by dehann** [comment]
Makie.jl + three.js is an awesome idea!

**Comment by SimonDanisch** [comment]
Yeah, we've chattet about this extensively ;) 
Actually, the very first prototype for WGLMakie was using Meshcat, but I quickly found that it was missing features... Also, MeshCat uses the threejs json interface, which is not as well tested and had bugs for more advanced features, which didn't get fixed in threejs in the time frame I was trying to get it to work.
Btw, we've also been working on getting the meshcat use cases working in WGLMakie:
https://nextjournal.com/sdanisch/taking-your-robot-for-a-walk

**Comment by SimonDanisch** [comment]
That was the issue btw: https://github.com/mrdoob/three.js/pull/14598, which seems fixed now!

**Comment by dehann** [comment]
Ah great, seems like I'm way behind then!
