### ISSUE TITLE
VS Code compatibility

### ISSUE THREAD

**Issue by oschulz** [JuliaPlots/WGLMakie.jl#44]
Could this be made to work with VS code? VS code displays should bring all the necessary functionality - there's SandDance plugin that uses WebGL in VS code extensively. But I don't know much about the internals.

@davidanthoff will know more about this.

**Comment by davidanthoff** [comment]
The VS Code plot gallery just pushes a custom display onto the normal multimedia display stack.

I'm not sure how WGLMakie.jl is implemented, but presumably giving VS Code a SVG or PNG won't do the trick, right?

**Comment by asinghvi17** [comment]
No, you would have to have a display capable of rendering WebGL, maybe through a webview or something.

**Comment by davidanthoff** [comment]
Our plot gallery is a web view.

Is the design that WGLMakie creates an HTML file from a plot? Or is there some communication going on between the web part and the Julia part of things?

**Comment by SimonDanisch** [comment]
There is a websocket connection which needs to be setup correctly

**Comment by davidanthoff** [comment]
So that won't work in principle, because for any communication between the webview and the extension we would need to use the VS Code native communication story, see https://code.visualstudio.com/api/extension-guides/webview#scripts-and-message-passing. Otherwise things won't work in the remote setup of VS Code.

Is that websocket connection be used continuously for communication between the Julia process and the webview, or just initial to transfer the plot over to the webview, and then it "ceases" to play a role in the communication?

**Comment by dlfivefifty** [comment]
Just tried this out... cool but the latency is pretty bad (I can count to "two-one-thousand" before the plot shows up)

**Comment by darsnack** [comment]
The latency wasn't awful for me, but it does not seem to work when using a remote machine via VS Code's Remote SSH extension. I assume something related to port forwarding needs to be set up?

**Comment by SebastianM-C** [comment]
You just have to forward 9284 and it works. On previous versions of VS Code, this was automatically happening, but now you have to manually forward.

**Comment by SimonDanisch** [comment]
VSCode is working now!
