### ISSUE TITLE
Display error in Pluto

### ISSUE THREAD

**Issue by grero** [JuliaPlots/WGLMakie.jl#73]
When running this notebook, the plot at the end fails to show up, and I get an error in the console.

```julia
### A Pluto.jl notebook ###
# v0.12.17

using Markdown
using InteractiveUtils

# ╔═╡ e28395e8-3dfa-11eb-18e0-118bbb139623
begin
	using Pkg
	Pkg.activate(dirname(@__FILE__))
	Pkg.rm("WGLMakie")
	Pkg.rm("AbstractPlotting")
	Pkg.add("AbstractPlotting")
	Pkg.add("WGLMakie")
	Pkg.status()
end

# ╔═╡ 21d26c38-3dfb-11eb-13b4-51e233cd1805
begin
	using AbstractPlotting
	using AbstractPlotting.MakieLayout
	using WGLMakie
end

# ╔═╡ 291d5746-3dfb-11eb-164a-8bc00a9860e5
let
	scene,layout = layoutscene(resolution=(500,500))
	la = layout[1,1] = LAxis(scene)
	x,y = rand(10), rand(10)
	scatter!(la, x, y, markersize=5px)
	scene
end

# ╔═╡ Cell order:
# ╠═e28395e8-3dfa-11eb-18e0-118bbb139623
# ╠═21d26c38-3dfb-11eb-13b4-51e233cd1805
# ╠═291d5746-3dfb-11eb-164a-8bc00a9860e5
```

This is the error:

```
From worker 2:	An exception was thrown in JS: Error: Error creating WebGL context.
      From worker 2:	Additional message: Error during running onjs callback
      From worker 2:	Callback:
      From worker 2:	function setup([scenes, duplicates]){
      From worker 2:	    const canvas = (document.querySelector('[data-jscall-id="1"]'))
      From worker 2:	    const renderer = WGLMakie.threejs_module(canvas, "9355818728995616480", 500, 500)
      From worker 2:	    WGLMakie.set_duplicate_references(duplicates)
      From worker 2:	    const three_scenes = scenes.map(WGLMakie.deserialize_scene)
      From worker 2:	    const cam = new THREE.PerspectiveCamera(45, 1, 0, 100)
      From worker 2:	    console.log(three_scenes)
      From worker 2:	    WGLMakie.start_renderloop(renderer, three_scenes, cam)
      From worker 2:
      From worker 2:	    function get_plot(plot_uuid) {
      From worker 2:	        for (const idx in three_scenes) {
      From worker 2:	            const plot = three_scenes[idx].getObjectByName(plot_uuid)
      From worker 2:	            if (plot) {
      From worker 2:	                return plot
      From worker 2:	            }
      From worker 2:	        }
      From worker 2:	        return undefined;
      From worker 2:	    }
      From worker 2:
      From worker 2:	    function add_plot(scene, plot) {
      From worker 2:	        const mesh = WGLMakie.deserialize_plot(plot);
      From worker 2:	    }
      From worker 2:	    const context = {
      From worker 2:	        three_scenes,
      From worker 2:	        add_plot,
      From worker 2:	        get_plot,
      From worker 2:	        renderer
      From worker 2:	    }
      From worker 2:	    put_on_heap('1', context);
      From worker 2:	}
      From worker 2:	Stack trace:
      From worker 2:	    Error: Error creating WebGL context.
      From worker 2:	        at new WebGLRenderer (https://cdn.jsdelivr.net/gh/mrdoob/three.js/build/three.js:17616:13)
      From worker 2:	        at Object.threejs_module (/Users/roger/.julia/packages/WGLMakie/QIWts/src/wglmakie.js:515)
      From worker 2:	        at Array.setup (http://127.0.0.1:8081/8fd0e412-0531-4dbd-884d-15ec84c0d9bb:44:31)
      From worker 2:	        at run_js_callbacks (/Users/roger/.julia/packages/JSServe/WVp6t/js_dependencies/core.js:196)
      From worker 2:	        at init_function (http://127.0.0.1:8081/8fd0e412-0531-4dbd-884d-15ec84c0d9bb:79:27)
      From worker 2:	        at init_from_byte_array (/Users/roger/.julia/packages/JSServe/WVp6t/js_dependencies/core.js:359)
      From worker 2:	        at XMLHttpRequest.http_request.onload (/Users/roger/.julia/packages/JSServe/WVp6t/js_dependencies/core.js:393)
```
This is the same notebook as I used when submitting [this issue](https://github.com/fonsp/Pluto.jl/issues/779), but it seems that after upgrading AbstractPlotting to 0.14.2, I get the above error instead.

**Comment by SimonDanisch** [comment]
This looks like your browser doesn't support webgl!

**Comment by grero** [comment]
Hm, that would be strange as I've running Pluto notebooks using WGLMakie for a while in this browser (Chrome). It was only after updating AbstractPlotting/WGLMakie/Pluto that things broke. It would be something else on my end though. I'll see if I can figure it out. In the meantime, CairoMakie works great, so I'll just switch to that backend for now.

**Comment by SimonDanisch** [comment]
I can't reproduce this. Can you try this in the REPL? It should open a browser window:
```julia
	scene,layout = layoutscene(resolution=(500,500))
	la = layout[1,1] = LAxis(scene)
	x,y = rand(10), rand(10)
	scatter!(la, x, y, markersize=5px)
	display(scene)
```
Make sure you're on:
```
WGLMakie v0.2.10
AbstractPlotting v0.14.2
```

**Comment by SimonDanisch** [comment]
If that works, I'm guessing Pluto has changed something.

**Comment by grero** [comment]
Yes, it does work. Thanks, I'll go ahead and close this and pursue the issue in the Pluto repo instead.

**Comment by SimonDanisch** [comment]
```
 Error creating WebGL context.
      From worker 2:	        at new WebGLRenderer (https://cdn.jsdelivr.net/gh/mrdoob/three.js/build/three.js:17616:13)
```
The only other thing that comes to mind here is, that it can make problems to create many WebGL contexts. So if you create lots of plots - or maybe trigger lots of updates in the pluto cell that creates the plot, the browser may decide to not hand out WebGL contexts anymore. This should also be across tabs, since I think the browser just globally hands out a limited amount of WebGL contexts.

From that error, it seems like a pretty clearly a browser error. If it gets to that point in JS, most things on the julia side & js loading side should have gone through successfully. Not sure what could have changed in Pluto to mess this up on that level!

**Comment by grero** [comment]
That's a good point, actually. I did end up having a lot of plots in the notebook I was working on (with lots of updates as I was tweaking the plots). I'll keep that in mind going forwards. Thanks a lot!

**Comment by SimonDanisch** [comment]
I need to look up the detailed rules (which probably vary by browser, which is why it's so fuzzy), but it should be the number of active WebGL contexts... So past plots shouldn't count, if the browser is freeing resources correctly :D And if the browser is good, it should also not count webgl context in other tabs / out of display - but maybe that's wishful thinking.

**Comment by grero** [comment]
Actually, not directly related to this, but I do find that I can only keep one active Pluto notebook using WGLMakie at a time. If I try to open several, I get the error `ERROR: IOError: listen: address already in use (EADDRINUSE)`. I assumed this means (in my limited understanding) that this means that the global process handling the Javascript stuff (?) can only handle one connection at a time?

**Comment by SimonDanisch** [comment]
You need to set https://github.com/SimonDanisch/JSServe.jl/blob/master/src/JSServe.jl#L45 to another port for each notebook:
```julia
JSSERVE_CONFIGURATION.listen_port[] = 8754
```
It's a bit annoying, but I found that opening a connection to a used port hangs indefinitely and I didn't find any method to figure out cross-platform if a port is already in use - so it's hard to change the port automatically.
But a looks a bit like the hanging got fixed in the newest julia version, so maybe I could start catching that error and try with a different port in that case.

**Comment by grero** [comment]
Ah, OK cool, I'll try that. Thanks again!
