### ISSUE TITLE
JupyterLab : outpout cell does not expand

### ISSUE THREAD

**Issue by chene-vert** [JuliaPlots/WGLMakie.jl#91]
**Configuration:**

- navigator :  Version 1.20.110 Chromium: 88.0.4324.192 (Build officiel) (64 bits)  (tested as well in chrome and firefox )
- Julia : 1.5.3
- WGLMakie : v0.3.3
- Jupyter Lab : Version 2.2.6

**Problem**
outpout cell does not expand

![image](https://user-images.githubusercontent.com/2108675/109308037-cc41be00-7841-11eb-891b-68de92cbb99e.png)

**Works with CairoMakie backend:**
![image](https://user-images.githubusercontent.com/2108675/109308216-03b06a80-7842-11eb-9a14-1601db86e562.png)

**Comment by SimonDanisch** [comment]
I haven't been able to install IJulia in years due to: https://github.com/JuliaLang/IJulia.jl/issues/1002#issuecomment-849100070
So I can't really test this... But in theory, this should work exactly like in Pluto with putting a cell in the beginning with:
```julia
using WGLMakie, JSServe
Page()
```
As explained in the docs: http://juliaplots.org/WGLMakie.jl/dev/#Pluto/IJulia
